version: '3.8'
services:
  shortly:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://shortly:shortly@db:5432/shortly?sslmode=disable
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shortly
      POSTGRES_USER: shortly
      POSTGRES_PASSWORD: shortly
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
